### ISSUE TITLE
スケジュールの変更ページ

### ISSUE THREAD

**Issue by FCAmiyamoto** [slbotbm/phase4#16]
従業員の「暇、プロジェクト作業中、近々終了予定」と
「プロジェクト名、空き」を変更できるようにする

**Comment by icepq** [comment]
必要な情報
- 名前
- 部門（フロント、バックエンドなど）
- 技術（言語名）
- 若手or熟練
- 現在進行中のプロジェクト名
- いつまでそのプロジェクトを行う予定か
